name: Docker Compose Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker Compose service
      run: docker-compose build

    # Add your tests or other checks here. For example:
    - name: Check if the services are up
      run: |
        docker-compose up -d
        docker-compose ps
        # Replace the next line with your actual test command(s)
        docker-compose exec your-service-name your-test-command

    - name: Shutdown Docker Compose services
      run: docker-compose down
